[network]
name = "devnet"
deployment_fee_rate = 10
stacks_node_rpc_address = "http://stacks-node:20443"
bitcoin_node_rpc_address = "http://bitcoin-node:18443"

[devnet]
docker_platform = "linux/amd64"

[accounts.deployer]
mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
